### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [DocOC86/embedding_svg_projectfile#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by DocOC86** [comment]
The functionality is the use of embedding SVG's within two clicks. If you have 20-50 SVG pics in a project, it would be a hard work to save for every style the SVG separately.
sorry for the late answer
